version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    
  app:
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    build: .
    command: ["npm","run","build"]
    depends_on: 
        - mongo
    ports:
      - "3000:3000"